- _config.yml
- _includes/default-footer.html
The footer looks like this with this PR: 
Once we got the domain name, we can also change the email in another PR
> Add twitter in contact info

- _posts/2019-09-24-application.md
@yochannah feel free to add the image there 😄
> Add story with the application

- about.md
- index.md
I reorganize a bit the index and about page.
@malvikasharan you can add the values in the "About" page
> Pathways and values

- _includes/default-header.html
- about.md
> Rename About page and create a "Participants" section with the values

- _includes/default-header.html
- index.md
Heya, I thought we can use this as a catchphrase that captures the gist of our program. What do you think?
> edited the front page short catchphrase

- _layouts/base.html
- js/scripts.js
On small screens, the navigation menu was only an hamburger menu on the top right but not clickable:
Now when clicking on the hamburger menu, it expands the full menu
> Add js to make navbar-burger (navigation) working on small screen

- about.md
- Engagement time for mentees and mentors (from the mountain of engagement)
Anything @malvikasharan to add?
> Add engagement details

- about.md
> Add benefits for mentors

- syllabus.md
> Add learning objectives in syllabus

- _includes/default-header.html
- index.md
- Reformulate a bit index page
- Update timeline
> Work on index page

- about.md
> Replace roadmap link by project board link

- CONTRIBUTING.md
Listed a few ways people can contribute
> adding ideas for contributions

- CODE_OF_CONDUCT.md
Using our official emails for this program: team@openlifesci.org
> added team email for coc reporting

- _data/partners.yaml
- _includes/timeline.md
- syllabus.md
> Partner ssi

- syllabus.md
split the syllabus open science week into 2, added one empty week
> adding 2 more weeks

- _includes/default-header.html
Removed value from the nav bar
> remove value from nav bar

- _data/people.yaml
Updated the last set of mentor and expert entries. Have to add Vicky's profile once she fills her data in.
> Added Vicky to the mentor list

- ols-1.md
> Fix links to weeks in ols-1 schedule

- _ols-1/week01.md
- _ols-1/week02.md
- _ols-1/week04.md
- _ols-1/week06.md
Try to fit with the assignments on the issue template (https://github.com/open-life-science/ols-1/pull/1)
> Update assignments for first weeks

- css/custom.scss
- ols-1.md
> Embed public google calendar in schedule

- _ols-1/week02.md
- _ols-1/week03.md
- _ols-1/week04.md
- _ols-1/week05-extra.md
- _ols-1/week06.md
- _ols-1/week08.md
- _ols-1/week10.md
- _ols-1/week11.md
- _ols-1/week13.md
- _ols-1/week15.md
I created a note file for each cohort call (empty for now) and add the link there (to avoid forgetting to add it later).
I also updated the assignments for week 03 and also resources for week 05
> Update syllabus with links to call notes and some assignments

- _config.yml
- _includes/default-footer.html
adds link to announcement-only google group: https://groups.google.com/forum/#!forum/ols-news
> add announcement mailing list 

- _ols-1/week10.md
- _ols-1/week11.md
Adding the correct schedule as planned next week.
> Update week 10 syllabus

- _ols-1/week14.md
Sorry for the quick merge! Reopening the PR for review.
> Update week-14 plan with 5 mins presentation

- _posts/2020-04-12-final-presentations-youre-all-invited.md
Reverts open-life-science/open-life-science.github.io#133
> Revert "Revert "final presentations blog""

- _posts/2020-04-12-final-presentations-youre-all-invited.md
- video on youtube, added the link below Yo's presentation
> Update 2020-04-12 with MS final-presentations

- _includes/ols-2-timeline.md
- index.md
> OLS-2: Open applications and add webinar details

- _ols-1/projects-participants.md
> Remove leftover from debug in participant display

- _data/partners.yaml
to be sure everything is politically fine
> Add missing Berenice's affiliation

- _data/ols-2-metadata.yaml
- _data/people.yaml
for the ones who answered the form
> Add experts and possible mentors for OLS-2

- index.md
Updated the landing page to reflect the current state of the project
- Major update in previously "why life science" section
- updated the OLS journey
- Some grammatical updates
> Updating the landing page to make it up to date

- _data/ols-2-metadata.yaml
- _data/people.yaml
- _includes/people.html
> Add extra mentors experts and display expertise information

- _data/people.yaml
OLS-1 round expertise for mentors
> Update people's expertise for OLS-1 entries

- _data/people.yaml
> Update bio for Jez Cope

- _data/people.yaml
Updated Mallory's information in people.yaml including:
* Added ORCID
* Added/modified expertise
* Added/modified life-science-expertise
> Update Mallory's information in people.yaml

- _data/people.yaml
No major changes, could stay as it was. Just changed the tense a bit to reflect that now I am in the new job, and tweaked a bit more.
> Changed text for Aidan Budd slightly

- _data/people.yaml
- _includes/people.html
> Merge life-science-expertise and expertise together

- _data/people.yaml
Hey, adding my data.
Thank you!
> adds lauracion

- _data/ols-2-metadata.yaml
- _data/people.yaml
...as requested in #164
@burkemlou could you check the changes if they are ok for you? Thanks a lot!
> Update @burkemlou details

- _data/people.yaml
Update Renato's profile.
Share this PR with others and ask them to update their profile.
> Update Renato's profile

- _data/people.yaml
Update Nicolas Palopoli's profile
> Update Nicolas Palopoli's profile

- _data/ols-2-schedule.yaml
> Add more mentor calls for OLS-2

- _data/ols-1-schedule.yaml
- _data/people.yaml
- _includes/week.md
- _ols-1/week01.md
- _ols-1/week02.md
- _ols-1/week04.md
- _ols-1/week05.md
- _ols-1/week06.md
- _ols-1/week07.md
- _ols-1/week08.md
- _ols-1/week09.md
- _ols-1/week10.md
- _ols-1/week11.md
- _ols-1/week12.md
- _ols-1/week13.md
- _ols-1/week14.md
- _ols-1/week15.md
- _ols-1/week16.md
- _ols-1/week17.md
- _ols-1/week18.md
- _ols-2/schedule.md
- ols-1.md
- ols-2.md
- Add resources (documents, slides, speakers) for each call in the schedule
- List speakers in cohort page
> Add resources and speakers for calls in cohort schedule

- _data/people.yaml
Adding profile as expert as part of OLS2, as per invitation.
> Adding my profile

- README.md
- _data/ols-1-projects.yaml
- _data/ols-2-projects.yaml
- _data/people.yaml
- _includes/default-header.html
- _ols-2/projects-participants.md
- _posts/2020-09-01-ols2-announcement.md
- bin/extract-people.py
- environment.yml
- ols-2.md
This PR should inlcude the following
> Updating people and projects for OLS-2

- _data/ols-2-metadata.yaml
- _data/ols-2-projects.yaml
- _data/partners.yaml
- _data/people.yaml
- H3ABioNet Open Learning Circles (OLC) has submitted two projects
> Add H3ABioNet Open Learning Circles (OLC) project and people

- README.md
- _data/ols-2-schedule.yaml
- _includes/overall-schedule.md
- _includes/week.md
- _ols-2/schedule.md
- Add date, notes and available resources
- Add documentation for schedule
- Fix some automatic schedule display
> OLS-2: update schedule and documentation

- _data/ols-2-projects.yaml
Due to the blockade encountered for the case-study in the previous proposal, the changes are proposed to execute the project without committing to the same case study. However, the replacement case study is currently being explored and will be communicated soon with the mentor and organizers. Meanwhile, please consider these changes to my proposal.
> proposing changes to the project

- ols-2.md
- ols-speaker-guide.md
This is an orphaned page - I wasn't quite sure where to link to it?
> add speaker guide

- _data/ols-2-projects.yaml
- _data/people.yaml
> off board Suliman from OLS-2

- _posts/2020-10-05-ally-skills-training.md
Add google form link and some minor update
> Add google form for discount request  in 2020-10-05-ally-skills-training.md

- _posts/2020-10-05-ally-skills-training.md
Updating as per our delivery materials
> Update one of the goals 2020-10-05-ally-skills-training.md

- _data/ols-2-schedule.yaml
- added ally skills to week-9 as a skill up session
- removed ally skills from career guidance call
- added skill-up for creative writing in week-13
> Update week-9 , week-11 and week-13 ols-2-schedule.yaml

- Gemfile.lock
- css/custom.scss
Hi!
This should fix the #179 
I'll be honest here, I don't have experience with Ruby related environments. I'm sorry the "Gemfile.lock" got modified as well automatically, I guess it's due to me, using Windows environment... Please let me know if you have any questions or concerns!
> fix issue #179

- ols-2.md
tiny fix - view it on the resources page for ols 2
> fixed broken twitter link

- _layouts/posts.html
- css/custom.scss
To fix #147
And also added a margin in top of post image:
Before | After
--- | ---
> Fix stories page

- _data/ols-2-schedule.yaml
Thank you for being so accommodating and flexible (:
> Updated time for week 9's cohort call

- _data/ols-2-schedule.yaml
- _data/people.yaml
- _includes/week.md
- ols-2.md
- Add hosts to calls to fix #203
- Add slide links, speakers, hosts
> Update of OLS 2 schedule 

- index.md
> Remove mention of open applications for OLS-2

- _posts/2020-10-05-ally-skills-training.md
each one linked to the link at the wrong time 😬
> registration links were swapped

- _posts/2020-11-26-announcing-applications-for-ols-3.md
> Announcing-OLS-3 and OLS-2 Graduations  🎉

- _includes/ols-3-timeline.md
> Add missing link to Easychair in timeline

- _posts/2020-12-18-ols-2-participant-emma-karoune-speedblog.md
thanks @ekaroune for authoring this!
> added @ekaroune's speedblog 😍

- _data/ols-2-schedule.yaml
- _data/people.yaml
- Fix #245 
- Add missing information, recording, resources for last calls
> Update OLS-2 schedule

- environment.yml
as it was messing up stuff for me locally
> Remove fixed ruby version in conda environment

- _data/ols-3-projects.yaml
some of the mentor/mentee pairs were slightly out of date compared to the spreadsheet. @malvikasharan you might want to double check as well, I didn't scan this fully and just checked my mentees :)
> added some mentoring tweaks

- _data/people.yaml
> add beth to data

- _data/ols-3-metadata.yaml
- _data/ols-3-projects.yaml
- _data/people.yaml
> Add Sam to data and mentor list

- README.md
- _data/ols-3-schedule.yaml
- bin/addevents.py
The script has reformated a bit the YAML file
> Add cohort details with a script

- _data/people.yaml
> Change emmy's affiliation and job title

- _data/ols-3-metadata.yaml
- _data/ols-3-schedule.yaml
- _data/people.yaml
Most links updated up to week 7! Please let me know if I missed something 💟 Documentations are crystal clear - thank you!
We have to add Helena and Andre to `people.yaml` before I can tag them as speakers. Do we have a workflow...?
> Add links up to week 7

- Makefile
- ols-2.md
- ols-3.md
> Fix link to weeks in syllabus pages

- _data/ols-3-schedule.yaml
- _data/people.yaml
> Add resources and recordings to week 16

- _posts/2021-06-28-ols-3-participant-Afzal-Ansari-speedblog.md
For [#36](https://github.com/open-life-science/ols-3/issues/36)
> Created speedblog for our project

- ols-4.md
> remove hardcoded months from the OLS-4 timeline 

- _data/people.yaml
> my bio was woefully out of date 😱

- _data/ols-4-projects.yaml
- _data/people.yaml
- _posts/2021-09-07-ols-4-annoucement.md
and fix some country names.
I just did not add keywords about the projects (I did have them as last time in the project sheet. OpenReview issue?)
> Add OLS-4 blog post

- _data/ols-4-projects.yaml
This is a very minor change, I just removed the last line regarding enrolling in OLS4.
> Change the description of our project

- index.md
plus direct people to sign up for the news list if they want ols-5 info
> remove application link for ols-4

- _data/ols-4-schedule.yaml
- bin/addevents.py
And add the possibility to update schedule from a complex CSV file (including slides, recording, etc)
> Update OLS-4 schedule 

- _data/ols-4-schedule.yaml
- bin/addevents.py
> Fix date reading in script to update schedule

- _data/ols-4-projects.yaml
- _data/people.yaml
This is a simple PR to add @LAlmehlisy to the project details - it also adds more details to the description of the project!
> Adding Leena to the Website

- _data/ols-5-schedule.yaml
- _includes/default-header.html
- _ols-5/speaker-guide.md
> Update OLS-5 schedule

- index.md
I forgot to add the changes in `index.md` in my last PR :woman_facepalming:
> Add OLS-5 details on index page

- _data/ols-5-schedule.yaml
- _posts/2021-12-13-ols-5-promotion.md
> Create a post for OLS-5 webinar, add link to the landing page

- _data/ols-4-metadata.yaml
- _data/ols-4-projects.yaml
- _data/people.yaml
Thanks @EstherPlomp for reminding us that we need to add Martin as a mentor for Arent!
@martlj would you mind taking a look at the info I've put in the YAML and see if they're correct? Please also feel free to suggest edits/additions! 🙏 Many thanks!
> Add Martin Jones as a mentor

- about.md
previously it said we were recruiting for the second round :)
> add OLS-4 and make phrasing slightly more generic

- about.md
we should also add facilitator lists for ols-3 and -4 and pull those into here (like we do with mentors and experts) - but unfortunately I don't have time now and I need this text for our invitations!
> Add text describing facilitator role

- _data/ols-5-projects.yaml
Luke sent his confirmation to attend
> Adding Luke andd updating his bio

- _data/ols-6-schedule.yaml
- _includes/default-header.html
- _includes/timeline.md
- bin/update_schedule.sh
- index.md
- Update schedule and timeline
- Add OLS-6 application button
- Add OLS-6 to header
> Making OLS-6 live

- _posts/2022-06-03-announcing-applications-for-ols-6.md
> update post to include correct openreview link

- index.md
Replacing the opening sentence to make it less technical
Suggestion for adding this image in the front page:
> update the opening sentence to make it less technical

- ols-4.md
- ols-5.md
- ols-6.md
- ols-7.md
- ols-8.md
> fix: correct wrong numbering of cohorts

- _data/ols-2-projects.yaml
- _data/ols-5-projects.yaml
- _data/people.yaml
- _layouts/default.html
- _layouts/posts.html
- _posts/2019-11-13-difference-with-elife-innovation-leaders.md
- _posts/2020-12-18-ols-2-participant-emma-karoune-speedblog.md
- _posts/2021-04-30-ols-2-participant-fez-speedblog.md
- _posts/2022-01-04-on-being-an-ols-mentor-in-2021.md
- _posts/2022-03-17-ols-4-participant-nadine-spychala.md
- _posts/2022-05-13-open-science-hobby.md
- _posts/2022-07-04-An-Incomplete-History-Of-Research-Ethics.md
- _posts/2022-07-18-ols5-speedblog-open-science-mooc.md
- Fix the author posts when they do not appear (mostly wrong id)
- Add link to author in the community page (would be helpful to check mistakes in the ids with link tests)
> Work on posts

- _data/ols-5-projects.yaml
- _data/people.yaml
- _posts/2022-08-09-ols5-speedblog-fair-datacheck.md
Adding a proofread draft of Frederique.
> FAIR data check in Open Access journals_Publication Steps

- .github/workflows/ci.yml
- Makefile
> Add better linting for links and GitHub Action for internal links

- _data/people.yaml
Disambiguating my role at OLS from that at IOI. They're separate engagements - I am in no way paid by IOI to work for OLS or the other way round. My positions at both organizations are separately funded and under separate contracts with my own private limited companies.
> Update Emmy's affiliation

- README.md
This PR fixes issue #428.
The README was meticulously examined for errors and the grammar was also minimally restructured. 
Kindly review. Thank you!
> Proofread and correct typos

- about.md
The screenshot below shows the errors detected in red circles and line. Kindly review
> grammatical error in the facilitators section corrected

- _data/ols-4-metadata.yaml
- _data/ols-5-metadata.yaml
- _data/people.yaml
> Bio and facilitator name update

- _data/ols-1-schedule.yaml
- _data/ols-2-schedule.yaml
- _data/ols-3-schedule.yaml
- _data/ols-4-schedule.yaml
- _data/ols-5-schedule.yaml
- _data/ols-6-schedule.yaml
- _data/ols-7-schedule.yaml
- _data/ols-8-schedule.yaml
- _includes/overall-schedule.md
- _includes/timeline.md
- _includes/week.md
#416 Work In Progress for time conversion.
> fix: CET to UTC times

- css/custom.scss
Corrected the spelling
`I made three changes`
``` diff
- shadown
+ shadow 
```
> Correct spelling

- _data/people.yaml
This pull request solves #506 .
It the details overflow the member card and the website link is placed in the affilations.
> Fix: overflowing user details.

- _data/ols-4-schedule.yaml
- _data/ols-6-schedule.yaml
Changes from Git pages to GitHub Pages in line 222
> Chimatara patch 1

- _data/ols-7-schedule.yaml
- index.md
Application clinic link is missing: https://www.eventbrite.co.uk/e/application-clinic-call-qa-tickets-506693121767
> Add application clinic link

- .github/ISSUE_TEMPLATE/weekly-checklist.md
- See example: https://github.com/open-life-science/open-life-science.github.io/issues/544
> Update weekly-checklist.md to include responsibilities for call lead, facilitator and cohort coordinator

- _data/people.yaml
To be able to automatically extract information including continents
> Fix country names in people.yml file

- _data/ols-4-schedule.yaml
- css/custom.scss
I reverted the changes I made in the bulma/css file. I was able to fix the contrast error in issue #439 by making the changes in the custom.scss file.
> Contrast error in issue #439

- _data/ols-7-projects.yaml
- _data/people.yaml
> Add a project from OLS-6 came back in OLS-7

- _data/ols-7-schedule.yaml
- _data/ols-8-schedule.yaml
- _includes/default-header.html
- index.md
> OLS-8 opening

- _includes/default-header.html
- consulting.md
I think we need to add the link to the menu too. and maybe a Table of Contents?
> add ally skills prospectus

- _data/community.yaml
- _data/people.yaml
- _includes/default-header.html
- _includes/people.html
- community.md
- Add Taj to people file
- Add title to team members
- Add team members to team page
- Fix title display in people box
> Update team page

- _data/funding.yaml
> added TOPS and Turing SPA and ecb/catalyst

- _data/openseeds/ols-8/metadata.yaml
- _data/people.yaml
> Update OLS-8 experts

- _posts/2023-12-07-Latin-American-students-drive-innovation-with-open-data.md
In this pull request, a new post has been added to the website in response to a request by @pherterich.
The content, originally shared by the [Software Sustainability Institute](https://www.software.ac.uk/), is authored by R. Camacho Toro, Y. Briceño, and A. Martínez. An image related to the post has also been included, as in the original post.
*Note for reviewer:*
Thank you!
> Crosspost SSI's Blog Post

- .gitignore
- _data/people.yaml
This PR shows an attempt to add people to the website, guided by the beautifully-documented [Knowledge Management System](https://openlifesci.org/knowledge_management.html) (thank you, Bérénice!).
B.B provided a `.csv file` from civi containing some new community members.
With this,
- I set up a virtual environment, 
- installed dependencies, 
- ran the python scripts and 
- added new people to the website.
_Success Screenshots!_ 🎉
**Note for reviewers:** The plugins are making it take a bit longer to serve up the site...and it is trying to kill my computer. 😆😭
> Trial Run: Add people

- _data/community.yaml
- _data/people.yaml
- _includes/default-header.html
- governance.md
This PR fixes issue #742.
- Included the Governance Committee members' ids in the `community.yaml` file.
- Added and/or updated their biodata (affiliation) in the `people.yaml` file.
- Created a new page, `governance.md`, to display their information.
- Added a direct link to the page from the navbar (`default-header.html`).
**Screenshot:**
**Preview changes [here](https://deploy-preview-743--ols-bebatut.netlify.app/governance)...**
**Note for reviewer:**
I maintained the same image used in the `/team` page, 98% for consistency and 2% for convenience.
We can also explore alternatives like these ([1](https://www.flickr.com/photos/missouristate/5051766452/), [2](https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?))...
Thanks a lot for the review!
> Create Governance page

- nebula/index.md
> Fix nasa redirect

- openseeds/about.md
very aged reference, probably from ols-1 times!
> remove reference to bioinformaticians

- _data/community.yaml
Community member, Rowland Mosbergen, recently joined the core team as an OLS fellow.
In this PR, his id has been added to "current team members" section, to provide visibility on the website.
**[Deploy preview here](https://deploy-preview-784--ols-bebatut.netlify.app/community)...**
> Add new fellow to the "team" page.

- _data/openseeds/library.yaml
- _data/openseeds/ols-7/schedule.yaml
- openseeds/library.md
> Fix bug in BioSchema implementation

- _data/community.yaml
- _data/openseeds/ols-3/schedule.yaml
- _data/openseeds/ols-5/schedule.yaml
- _data/openseeds/ols-7/projects.yaml
- _data/openseeds/ols-7/schedule.yaml
- _data/people.yaml
- _posts/2024-07-12-RSE-AUNZ-joins-OLS.md
> Technical review of PR #804

- _includes/default-footer.html
apparently we shouldn't use this word unless we're a registered charity, even though we are not-for profit
FOR CONTRIBUTOR:
FOR REVIEWERS:
> remove "charitable"

- _data/organizations.yaml
Small pr that updates WT and gives us the chance to see if our new PR notification pipeline works! 
FOR CONTRIBUTOR:
FOR REVIEWERS:
> update the description of the wellcome trust

- .github/pull_request_template.md
I like hyperbole
FOR CONTRIBUTOR:
FOR REVIEWERS:
> the funkiest PR template you ever did see

- _posts/2024-07-15-openseeds-in-2024.md
PR fixes issue #808.
A blog post explaining the current state of OLS-9 operations has been added to the website.
**[Deploy preview..](https://deploy-preview-811--ols-bebatut.netlify.app/posts/2024/07/15/openseeds-in-2024/).**
> Add OLS-9 blog

- _includes/default-footer.html
Addressing #199 
.I added a google translate button which allows the web pages to be translated into different languages.
> Added a google translate button to the footer section

- _data/openseeds/ols-3/projects.yaml
- _data/openseeds/ols-4/projects.yaml
- _data/openseeds/ols-5/projects.yaml
- _data/openseeds/ols-6/projects.yaml
- _data/openseeds/ols-7/projects.yaml
Add missing graduated status to a bunch of projects
PR Type: 
> Add graduated status to a bunch of projects

- _posts/2024-07-24-welcoming-resident-fellow-seun-olufemi.md
**This PR fixes issue #849.
A welcome blog post has been added for @seunolufemi123!** 🎉 
See screenshot below:
PR Type: 
> Add Seun's welcome blog post

- _posts/2024-07-24-welcoming-resident-fellow-seun-olufemi.md
- _posts/2024-07-29-welcome-resident-fellow-seun-olufemi.md
This PR fixes …#861.
PR Type: 
> Cross-link Pidgin and English version of Seun's blog post

- nebula/index.md
Update Nebula landing page with info for the new cohort.
@NPDebs , I'm happy with the content, but need a technical review.
PR Type: 
> Update Nebula landing page

- _data/openseeds/ols-1/projects.yaml
- _data/openseeds/ols-2/projects.yaml
- _data/openseeds/ols-3/projects.yaml
- _data/openseeds/ols-4/projects.yaml
- _data/openseeds/ols-5/projects.yaml
- _data/openseeds/ols-6/projects.yaml
- _data/openseeds/ols-7/projects.yaml
- _data/openseeds/ols-8/projects.yaml
Update Open Seeds project status and keywords
PR Type: 
> Update Open Seeds project status and keywords

- nebula/about.md
- Update about.md with info for upcoming cohort. 
- Add links to registration form. 
- Deleted button for expert registration.
- Clarified pricing
Please review html format.
PR Type: 
> Update about with info for new Nebula cohort

- policies-procedures-and-docs/communications/slack-guide.md
> Tweak public slack guide

- _includes/nebula-header.html
- nebula/about.md
- nebula/index.md
This PR:
* Renames `about.md` -> `index.md` and vice versa, ensuring that the landing page is correctly found in the index.md file
* Updates nav bar logo and Program tab to point to the correct files, after the renaming
* Updates `about.md` with Nebula program information, including roles and syllabus. This removes the content redundancy with the index.md file
@yochannah , could you help with a technical review? 
PR Type: 
> Rename index.md and about.md in Nebula subsite

- .github/workflows/ci.yml
- .github/workflows/update-bibliography.yml
- _data/openseeds/library.yaml
- _data/openseeds/ols-3/schedule.yaml
- _data/openseeds/ols-8/schedule.yaml
- _data/openseeds/ols-9-catalyst/schedule.yaml
- _data/openseeds/ols-9-dra/schedule.yaml
- bin/openseeds/update_schedule.sh
- bin/prepare_website_data.py
Fix #879 with errors mostly introduced in #867
PR Type: 
> Fix schedule update

- _data/openseeds/ols-9-catalyst/schedule.yaml
- _data/openseeds/ols-9-dra/schedule.yaml
Some dates were wrong in OLS-9 DRA schedule because they were added to the schedule file before changes in the spreadsheet and the script did not merge them.
@malvikasharan could you check if everything is in order now? Thanks a lot
PR Type: 
> Fix OLS-9 DRA and catalyst schedules

- _data/openseeds/ols-9-catalyst/schedule.yaml
- _data/openseeds/ols-9-dra/schedule.yaml
The CI was failing because of some issues in the extracted schedules.
@malvikasharan  I updated the spreadsheet and re-run the schedule extraction
PR Type: 
> Fix OLS-9 schedules

- nebula/nebula-cohort-procedures/nebula-microgrants.md
This PR adds a copy of the OLS microgrant policy to the Nebula subsite, to be more easily updated and adapted for Nebula. 
PR Type: 
> Add nebula microgrant policy

- 2024-10-31-introducing-the-catalyst-project-community-partner-highlights.md
> Add blog post, "Introducing the Catalyst Project..."

- nebula/index.md
I replaced Humanitix links with the fee waiver request form to allow people to register before we finalize dates for the next cohort, as I met some people who might want to join. I also changed cohort dates.
@yochannah, could you check that the language reflects what we discussed about cohort dates for next year? Please make any necessary changes.
Also tagging @NPDebs for technical review, including checking that the links go to the fee waiver request form 🙏 
PR Type: 
> Update links and dates

- policies-procedures-and-docs/payments/honorarium.md
Addressing https://github.com/open-life-science/internal-policies-and-procedures/issues/164
PR Type: 
> Update honorarium policy FAQs

- openseeds/cohort-procedures-and-templates/graduation-guide.md
Please review this updated version of graduation requirement
> Update graduation-guide.md to clarify criteria for OLS-9

- _events/2024-02-ordem.md
PR Type: 
In the events page, details about the KMS talk delivered at FOSDEM (ORDEM) does not include a link to the slides. This PR adds a link to the presentation.
> Add link to slides for FOSDEM (ORDEM) KMS talk

- nebula/index.md
Updating Nebula dates and registration links for upcoming cohort.
@yochannah, could you help with a technical review? 
PR Type: 
> Update Nebula dates and registration links

- _events/2024-02-ordem.md
Reverts open-life-science/open-life-science.github.io#940
goodness me.
> Revert "Revert "Add link to slides for FOSDEM (ORDEM) KMS talk""

- _data/openseeds/ols-9-dra/projects.yaml
Recieved a message from Soorena - and integrating changes here:
> I have just checked the OLS website (https://we-are-ols.org/openseeds/ols-9-dra/projects-participants.html), and I found out that the information for my project is wrong. FYI, I have provided the right one below for your review, and I would be grateful if you could modify that:
> Project: Introducing potential opportunities in applying DRI for research and building professional skills for persons living with visible and invisible disabilities
> By: Soorena Azarhazin
> Mentored by: Jez Cope
> Keywords: Computational Fluid Dynamics (CFD), Numerical Simulation Of Thermo-Fluids Processes, Flow Control
> Summary: My personal goal is to improve knowledge about and access to DRI to mitigate these barriers in several ways, …
> Update Soorena's info

- nebula/about.md
Update dates for new cohort
PR Type: 
> Update dates for new cohort

- _posts/2025-02-05-pause-on-nebula.md
- nebula/about.md
- nebula/index.md
- nebula/nebula-cohort-procedures/nasa-certification.md
- open-science-training.md
This PR re-brands Nebula according to current guidelines from NASA. 
PR Type: 
> Nebula pause and rebrand. 

- .github/workflows/deploy.yml
PR Type: 
Fixes #935. Workflow has been updated to use v3 of `upload-pages-artifact` and v4 `deploy-pages` action.
> Update workflow to use v4 of the artifact actions

- _data/community.yaml
Moves Flavio and MAyya to "Alumni". Also fixes a tiny typo. 
PR Type: 
> migrate inactive fellows to alumni

- _data/people.yaml
We upgraded Debs to community manager aaaages ago, this is overdue. 
PR Type: 
> Update Debs' Job title

- _data/people.yaml
Update Patricia's job title to reflect what she does. 
PR Type: 
> Update Patricia's job title

- _posts/2025-02-20-advancing-tbi-care.md
> Add blog post by OLS-9 participant, Sebastian.

- _posts/2025-02-20-advancing-tbi-care.md
In a previous PR which added this blog post to the website, `Sebastian Ayala Ruano` was erroneously added as author, when in reality, the post is by Sebastian D’Amario (id: `damario99`).
PR Type: 
> Credit correct author in OLS-9 speedblog

- _posts/2025-03-13-my-FOSS-backstage-experience.md
> Create FOSS-backstage blog post

- _data/people.yaml
> Update people.yaml for hrhotz

- _posts/2025-03-27-research-fellow-role.md
need to be approved by @yochannah and/or @pherterich
> Create research fellow role announcement

- _data/community.yaml
- _data/people.yaml
PR Type: 
Update @Camille-Gonzalez-VA's GitHub username (`camille-gonzalez-va`).
> Update Camille's GitHub username

- _config.yml
- _includes/default-footer.html
PR Type: 
This PR fixes issue #984, which requested that the OLS youtube and Linkedin channels be added to the website footer.
> Add social media icons to the website footer

- _posts/2025-04-30-from-mentee-to-resident-fellow.md
This PR resolves issue [#338](https://github.com/open-life-science/internal-policies-and-procedures/issues/338), where Doaa submitted her blog post draft for review and publication.
Post to be featured in this Friday's newsletter (May 2).
PR Type: 
> Add Doaa's Resident Fellowship reflection blog post 

- _posts/2025-05-07-ols-governance-report.md
> Add OLS Governance Committee report blog post

- _posts/2025-06-04-ols-retreat-debs.md
The core team has agreed to co-author another reflection post - plans are underway for this.
PR Type: 
> Add a shiny, new blog post for the team retreat (Debs).

- _posts/2025-06-04-ols-retreat-debs.md
This PR debugs an existing blog post, crediting the right author, Debs, for her image.
PR Type: 
> Debug: Credit the right author, Debs, for her image.

- _posts/2024-12-11-ols-dra-ospark-announcement.md
Updates the OSPARK announcement blog to include an updated newsletter signup link. Also adds a signup form.
PR Type: 
> OSPARK newsletter embed and link

- _includes/default-footer.html
Fixes #929, by adding an NGOSource ED Badge to the footer of our website. 
PR Type: 
> Add NGOSource ED Badge to website footer

- _posts/2025-08-01-reflections-on-neuroseeds.md
> Add past Resident Fellow, Sara's reflections on Open Neuroseeds

- Gemfile.lock
- _data/community.yaml
- css/custom.scss
The commit titles are sufficiently descriptive I think :) mostly content changes (including the bugfix for #1051 which apparently was due to content that didn't match the template). 
PR Type: 
> Fsc tweaks - make images smaller, add wording, and fix a bug

- _posts/2025-08-22-ols-is-hiring-fsc-manager.md
> add fsc hiring ad
