open-life-science/open-life-science.github.io

- _data/people.yaml
Fotis notified me that his handle was wrong in my tweet which was because we had his info wrong here 😭 But he said he doesn't mind the wrong profile @fpsom as they may gain some open life science followers 😃
> Correcting Fotis's twitter handle

- _includes/default-header.html
- index.md
Removed the cohort call tab from the front page header as it is a page of its own now
> remove a non functioning tab from header

- _includes/overall-schedule.md
- about.md
1. Mentors and experts are only listed in the cohort page not in the about page (link to cohort pages)
2. Calendar is display using the planning view in schedule page
> Small fixes

- _includes/default-header.html
- It isn't clickable at the moment
- The link can be updated with the most recently concluded cohort
> Update default-header.html to make previous OLS clickable with the last cohort

- community.md
- css/custom.scss
It is available under `/community` (not linked from anywhere), to help creating "Acknowledgement" slide
> Add community page with avatars of all people

- _data/ols-2-projects.yaml
- _data/people.yaml
@paulowoicho is joining The Turing Way project and hence will join the OLS-2 project on embedding accessibility.
This PR adds him to the project page, a PR should come from him adding details about him.
> Add paulowoicho in The Turing Way project

- Gemfile
- Gemfile.lock
- _config.yml
- _ols-2/speaker-guide.md
- ols-2.md
I moved the speaker guide of OLS-2 folder (as it was introduce this way). To avoid any issue with links, I added a plugin which redirect the previous location to the new location.
I also worked on the internal links there.
> Some work on speaker guide

- _includes/ols-3-timeline.md
Time: 12:00 CET/11:00 UTC
- Notes: https://tinyurl.com/ols-3-webinar
- [arewemeetingyet link](https://arewemeetingyet.com/London/2021-01-04/11:00/OLS-3-Webinar#eyJ1cmwiOiJodHRwczovL3Rpbnl1cmwuY29tL29scy0zLXdlYmluYXIifQ==)
> Update ols-3-timeline with webinar link

- _data/people.yaml
- _includes/people.html
- _layouts/community.html
- community.md
- css/custom.scss
This PR:
- Fix #210 with on the top only avatar and then details about people
- Add information about roles in the different cohorts, extracted from the files in `_data`
In community page, roles are extracted and displayed before the expertise:
Roles are not visible in other pages (too much to extract every time):
Current scripts should be optimized (too much redundancy) - but later
> Add people info to community page

- README.md
- _data/ols-1-metadata.yaml
- _data/ols-1-projects.yaml
- _data/ols-1-schedule.yaml
- _data/ols-2-metadata.yaml
- _data/ols-2-projects.yaml
- _data/ols-2-schedule.yaml
- _data/ols-3-metadata.yaml
- _data/people.yaml
- bin/extract-people.py
- bin/sort-expertises.py
- css/custom.scss
- js/scripts.js
- ols-3.md
This PR:
- Add possible mentors and experts
- Fix #249: Organize mentors and experts in cohort page by expertise areas (not perfect)
> First round of addition of registered experts and mentors

- Makefile
- README.md
- _data/ols-4-metadata.yaml
- _data/ols-5-metadata.yaml
- _data/ols-5-projects.yaml
- _data/people.yaml
- _posts/2022-03-03-ols-5-annoucement.md
- bin/add_mentors_experts.sh
- bin/prepare_website_data.py
- environment.yml
also update the script to add a command to add possible mentors / experts to a cohort (add to `people.yaml`, add to metadata file of the cohort, extract expertise)
Fix: #345
> OLS-5: add people, project and also announcement post

- _data/organizers.yaml
- _data/people.yaml
- _includes/default-header.html
- about.md
Adds an organisers section to the main page - I didn't realise Emmy wasn't on there! 😱  and adds Paz too. 
Marking as WIP - @pazbc, I think we need your bio for this, same as what we've been asking OLS-6 participants for.
> Add organisers section as well as founders section to about page

- css/custom.scss
This PR fixes issue #420.
The width of the table had caused other elements to have too much space on the right.
My solution was to write media queries using breakpoints between 768px to 320px. A reduction in `font-size` (and slight increase in `line-height`, to ensure readability), seemed to do the trick.
Additionally, this approach fixed alignment issues across other pages containing tables.
<br />
> Fix Table Overflow

- css/custom.scss
Signed-off-by: Deborah Udoh <deborahudoh02@gmail.com>
This PR fixes issue #238.
An easy, straightforward solution to prevent the content of `<section class="hero">` from overflowing, is to give it a height of `auto`, rather than a fixed height.
Please review this and suggest additional changes where necessary. Thank you!
> Prevent Overflow of Text from Header 

- css/custom.scss
closes #488 
This aligns text and avatars by their middle.
It was looking a bit messy, so I just added a `vertical-alignment` to `people-badge `
> Issue488: Fix multiple authors text and avatar alignment

- _data/ols-1-projects.yaml
- _data/ols-2-projects.yaml
- _data/ols-3-projects.yaml
- _data/ols-4-projects.yaml
- _data/ols-5-projects.yaml
- _ols-1/projects-participants.md
- _ols-2/projects-participants.md
- _ols-3/projects-participants.md
- _ols-4/projects-participants.md
- _ols-5/projects-participants.md
- _ols-6/projects-participants.md
- _ols-7/projects-participants.md
- _ols-8/projects-participants.md
- _posts/2020-05-27-ols1-wrapup.md
closes #198 
This adds a `status` field for each project's participant.
I added the `status` inside an `if clause` to the `projects-participants.md`. I did this because we don't have all the status** data yet. This way the `status` will only show if it exists inside the `ols-x-projects.yaml`.
If this is ok, we could update the structure with this PR, and I can open a new issue to update the YAML files when the data is available.
** about the the status data: As @AndreaSanchezTapia pointed out, I found the `graduated:true` field, but only in the `ols-1-projects.yaml`
without status
with status
> Issue198: add project participant status to projects

- _data/ols-3-metadata.yaml
- _data/ols-3-projects.yaml
- _data/ols-4-metadata.yaml
- _data/ols-4-projects.yaml
- _data/ols-6-projects.yaml
- _data/people.yaml
This PR fixes issue #504.
I merged the information about people with double profiles.
In addition, I noticed and corrected:
- an error in a member's **`expertise`** section.
- an omission of pronoun.
- a typo in `country` section.
> Resolve members with double profiles

- _includes/people.html
- _layouts/people.html
This PR fixes, in part, issue #418.
The role of each member is now being displayed on their cards, as desired.
Please review these changes. Thank you!
> Display the roles of members in their bio.

- _data/ols-7-schedule.yaml
- _includes/overall-schedule.md
- bin/prepare_website_data.py
- environment.yml
- Use ruamal.yaml instead of pyyaml in Python script
- Force double quote for time
> Modify schedule to double quote all times and avoid 540 on website

- css/custom.scss
This PR piggybacks on #441.
It fixes issue #433.
A lovely improvement was made on the card by @oluwatobiBolu. I added a fixed height to the text, which further aligned the card content.
*Note for reviewers:* The `text-decoration: green;` has been removed. To know which texts are links is now difficult to tell.
> Resolve alignment on "posts" cards

- about.md
This PR addresses issue #558.
Past behaviour: 
A bug messed with the count for OLS-6 projects.
Current behaviour:
The correct number of project is being displayed.
> Fix number of OLS-6 projects & add OLS-7 projects

- _layouts/base.html
- _layouts/post.html
This PR resolves issue #591.
A script was added to automatically generate structured data for all the pages with the layout "post." This should help our blogs rank higher in searches.
**Note for reviewers:**  See also the suggested fix for a similar PR (#469). Thank you!
> BlogPost Schema Annotation for Posts

- ols-8.md
it said something like: "ambassadors from european countries and bioinformatics" and I changed to so it says "countries and all science fields"
> change-ols-8-description

- CONTRIBUTING.md
- _config.yml
- _data/links.yaml
- _posts/2020-03-16-covid-response.md
- _posts/2021-12-13-ols-5-promotion.md
- _posts/2021-12-21-wt-open-research-fund.md
- _posts/2022-01-27-runway-to-sustainability-czi-funding.md
- _posts/2022-12-14-OLS-Fellowships.md
- _posts/2022-12-15-OLS-SSI-Fellows.md
- _posts/2023-06-12-ols-7-graduations-and-ols-8-call.md
- consulting.md
This PR addresses issue #659, in part.
The website email is now _team@we-are-ols.org_, rather than _team@openlifesci.org_.
**Future action:** Update URL as well (as soon as we-are-ols.org starts to work).
> Update email: team@we-are-ols.org

- _ols-2/speaker-guide.md
- _ols-3/speaker-guide.md
- _ols-4/speaker-guide.md
- _ols-5/speaker-guide.md
- _ols-6/speaker-guide.md
- _ols-7/speaker-guide.md
- _ols-8/speaker-guide.md
- _posts/2020-10-05-ally-skills-training.md
This PR addresses part of issue #659.
In PR #660, the website email was changed from [team@openlifesci.org](mailto:team@openlifesci.org) to [team@we-are-ols.org](mailto:team@we-are-ols.org).
Here, the email addresses of organisers have been changed as well.
**Future action:** Update website URL as well (as soon as we-are-ols.org starts to work).
> Change organisers' email address in schedule page

- _data/consulting.yaml
- _includes/default-header.html
- consulting/accessibility-consulting.md
- consulting/ally-skills.md
- consulting/index.md
This PR addresses issue #678.
Following the request to add more consultancy services to the website, a new index page is now under construction.
1. Created a `/consulting` subfolder to house all the individual services offered by OLS.
2. Added an `index.md` file to the newly created subfolder which will be the new landing page.
3. Stored the information about services in a `consulting.yaml` file.
4. Displayed the stored information on small cards in the index page (i.e /consulting). On these cards are links to individual services.
5. Used separate _service-x.md_ files for more consultancy pages (with url `/consulting/ally-skills`).
**Questions/Comment for reviewer(s):**
1. Is there any info missing from the cards that should be added?
2. Currently, the same hero image is …
> Expanding consultancy page(s)

- _includes/default-footer.html
This PR addresses the issue of the wrong Github profile in the website's footer.
**Observed behaviour:**
In the footer is a [link](https://github.com/htmluke) that should ideally lead to the Github profile of the creator of OLS's logo.
The current link found there leads to a **404 page**. 
**Expected behaviour:**
A link to the [actual github account](https://github.com/lukethebaka) has been used to replace the other.
Thanks for the review. 🙏
> Update github link of logo creator

- knowledge_management.md
In the [Knowledge Management System](https://openlifesci.org/knowledge_management.html) page, the link provided does not link to OLS's GitHub repository. This happened because  `{{ site.owner_url }}` environmental variable was used, rather than `{{ site.github.repository_url }}`.
This PR addresses the issue by specifying the necessary variable.
Thanks for reviewing!
> Link to OLS GitHub repo from KMS page

- bin/prepare_website_data.py
This PR relates to a minor issue observed in #736, which is the capitalisation of names.
Names inputed by community members on civi ought to be formatted properly to ensure consistent capitalisation in all fields.
*Changes made:*
First, I added the `.capitalise()` method, but that didn't do the job, since it only capitalised the first letter of the string.
So, the `.title()` method  has been applied instead, to improve readability.
*Note for reviewer(s):*
I also corrected a typo in the scripts. :)
Thanks for reviewing!
> Automatically capitalise names

- _includes/default-header.html
This PR is necessitated by Yo's comment about making it easier for community members to locate the logos (and other assets).
So, a new dropdown item `"branding"`, which links directly to the [branding repo](https://github.com/open-life-science/branding), has been added to the navbar.
_See screenshot below:_
Thanks for reviewing!
> Link to branding repo from navbar.

- _includes/streams.md
- css/custom.scss
- index.md
This PR fixes item (b) of issue #709.
The cards previously occupied different heights in the [homepage](https://openlifesci.org/) and other _three pillars_ pages.
This caused an inconsistency in the design and was not very aesthetically pleasing.
- Added a new class `three-pillars` to target and selectively style these cards.
- Tweaked the CSS as follows, to make the cards equal:
```
@media (min-width: 780px) {
...
.container .columns.three-pillars .column .card {
height: 100%;
}
}
```
Preview [here](https://deploy-preview-741--ols-bebatut.netlify.app/)...
> Make "three pillars" cards occupy equal height

- community.md
This PR fixes a tiny typo that was spotted in the [teams](https://openlifesci.org/community.html) page, as seen below:
The typo "os" was changed to "of."
Thanks!
> Fix typo in "teams" page.

- _data/community.yaml
- community.md
This PR addresses issue #774.
- A nested list was created to differentiate "current" from "past" team members.
- Add a section for "Former team members.
**Deploy [preview here](https://deploy-preview-776--ols-bebatut.netlify.app/community)...**
**Note for reviewer(s):**
Like Yo mentioned, this may not be the most appropriate wording. So, suggestions are welcome.
> Update staff page to include  "former members" section.

- _includes/streams.md
This PR addresses issue #781.
Under the "Key personnel" section, the GitHub links did not include ids for each individual. As such, it only lead to the url `https://github.com/`, rather than the relevant profile(s).
This was also observed in all pages displayed using the [streams.md](https://github.com/open-life-science/open-life-science.github.io/blob/main/_includes/streams.md) include file (e.g [open-incubator)](https://openlifesci.org/open-incubator.html).
- Within the loop, a line that assigns the `username` variable to the value of each `entry` was added.
- The value of `username` was set to `username`.
**[Deploy preview link](https://deploy-preview-785--ols-bebatut.netlify.app/open-research)...**
> Fix bug preventing GitHub links from working right.

- _consulting/organisational-leadership.md
- _events/2024-10-research-software-engineer-training-course.md
This PR resolves issue #791.
To the existing [consulting](https://openlifesci.org/consulting/organisational-leadership/) page, a section has been added, with information about the Research Software Engineer (RSE) Leadership Training Course.
[Deploy preview](https://deploy-preview-792--ols-bebatut.netlify.app/consulting/organisational-leadership/#research-software-engineer-rse-leadership-training-course) here...
**Note for reviewer(s)**
- I haven't linked to the training materials yet. Are we ready to go live with it.
> Add course description for RSE Leadership Training.

- _events/2024-10-research-software-engineer-training-course.md
Fix Rowland's id in RSE Training Course event
PR Type: 
> Fix rowland id in RSE training course

- _config.yml
This is the jekyll change to implement we-are-ols.org rather than openlifesci.org :) 
PR Type: 
> migrate from openlifesci.org to we-are-ols.org

- _layouts/links.html
- css/custom.scss
This PR fixes issues #617 and #638.
1. Swapped the `#48b87d` for `#265F3F` to improve the contrast across the website.
- This passed the Wave accessibility test
- It changed the colour of the green link underline and the background colour in the links page.
2. Updated the OLS logo in the `/links` page.
3. Altered the styling page for the `/links` page. Hopefully, it doesn't work only on my end, as in #687 
**Screenshots**
_Contrast fix:_
_Links background:_
_Responsiveness:_
PR Type: 
> Fixed contrast errors and responsiveness

- policies-procedures-and-docs/communications/slack-guide.md
> add OLS internal team rituals to the slack page

- _config.yml
- _includes/nebula-header.html
- nebula/nebula-cohort-procedures/nasa-certification.md
This PR adds a file explaining the NASA certification process to the Nebula cohort processes and procedures folder. 
- Tagging @doaamkader for content review: Are the steps clear? Any questions we should anticipate?
- Tagging @NPDebs for technical review after content approval. 
PR Type: 
> Add NASA certification process

- _events/2024-02-ordem.md
Reverts open-life-science/open-life-science.github.io#927
I think this is where teh build broke
> Revert "Add link to slides for FOSDEM (ORDEM) KMS talk"

- _posts/2025-04-03-ols-values-draft-for-review.md
Blog for value draft is ready for review.
Connected to issue on Gov repo https://github.com/open-life-science/ols-governance/issues/12
Review needed from at least 1-2 people in the OLS team of governance.
This blog should be published and communicated to our community on 7 April.
> Create value draft blog

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy.yml
This PR fixes #994 - thanks again for flagging, Yo!
In #948, a new GitHub Action was added, which primarily provides a live deploy preview link under each open Pull Request.
However, the previous Action that handled deployment to GitHub pages was removed in the process. This PR addresses the resulting effects of that...action. :-)
PR Type: 
> Debug: Restore website deployment to GitHub Pages 

- .github/workflows/deploy-preview.yml
This PR is an extension of functionality introduced by the action in #948, where a PR preview workflow was implemented.
Previously, the action only allowed a single PR preview (i.e. the latest one) to be available per time because it overwrote the entire content of the _gh-pages_ branch, with the new changes. Here, the deploy action has been modified to accomodate previews for multiple open Pull Requests.
PR Type: 
> Improve pr-preview action to accomodate previews for multiple open PRs

- fiscal-hosting/fsc-policies.md
This PR updates FSC documentation to clearly link to our budget template. 
PR Type: 
* This PR does something else (explain above)
> add budget template for fscs

- _consulting/ally-skills.md
> typo: loooking -> looking
